-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgWMlCtvdhq/IETb39
XEj7yqnXqCsS3vvBvBTo0dlUDMagCgYIKoZIzj0DAQehRANCAASQKOaQcfHPdAYf
y1pfGeEQVmIzobvSsEq2wdPMiJ2qXAmK44G2Ffv+g+X9t2kYFDbpVNi5pqVLVFOc
PTLel/Hv
-----END PRIVATE KEY-----